name: "README"
on:
  schedule:
    - cron: '*/23 * * * *'
  push:
    branches:
      - 'main'

jobs:
  Update-profile:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README.md
        run: |
          echo "[![README](https://github.com/fioravera/fioravera/actions/workflows/README.yml/badge.svg)](https://github.com/fioravera/fioravera/actions/workflows/README.yml)
          
          " > README.md
          date >> README.md
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update"
          git push origin main
