name: "update"
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - 'main'

jobs:
  update-readme:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update README
        run: |
          echo "[![Cronjob](https://github.com/fioravera/fioravera/actions/workflows/update-readme.yml/badge.svg)](https://github.com/fioravera/fioravera/actions/workflows/update-readme.yml)" > README.md
          echo "${{ date }}" >> README.md
      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update"
          git push origin main
