name: "Cronjob"
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - 'main'

jobs:
  update-weather:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: |
          echo "${ date }" > README.md
      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update"
          git push origin main
